[project]
name = "Bias-Prevention-LLM"
version = "0.1.0"
description = "Add a short description here"
channels = ["pytorch", "conda-forge", "https://conda.modular.com/max"]
platforms = ["linux-64"]

[tasks]

[dependencies]
transformers = ">=4.46.3,<5"
pytorch = ">=2.5.1,<2.6"
ipykernel = ">=6.29.5,<6.30"
python = ">=3.12.7,<3.13"
datasets = ">=3.1.0,<4"
sentencepiece = ">=0.2.0,<0.3"
sacremoses = ">=0.0.53,<0.1"
regex = ">=2024.11.6,<2024.12"
tqdm = ">=4.67.0,<4.68"
ipywidgets = ">=8.1.5,<8.2"
notebook = ">=7.2.2,<7.3"
huggingface_hub = ">=0.26.2,<0.27"
torchtext = ">=0.6.0,<0.7"
pandas = ">=2.2.3,<3"
scikit-learn = ">=1.5.2,<2"
peft = ">=0.13.2,<0.14"
rouge-score = ">=0.1.2,<0.2"
nltk = ">=3.9.1,<4"

[pypi-dependencies]
huggingface-hub = { version = "*", extras = ["cli"] }
